update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -48,7 +48,16 @@ jobs:
       - name: black - static security code check
         run: |
           pip install black
-          black --check --verbose .
+          black --check --verbose camera/.
+          echo "ErrorLevel: $?"
+          black --check --verbose common/.
+          echo "ErrorLevel: $?"
+          black --check --verbose door/.
+          echo "ErrorLevel: $?"
+          black --check --verbose messaging/.
+          echo "ErrorLevel: $?"
+          black --check --verbose fdia.py
+          echo "ErrorLevel: $?"
 
       - name: Wemake Python Stylguide
         uses: wemake-services/wemake-python-styleguide@0.13.4
